# Generated by Django 4.0.7 on 2022-08-04 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportation',
            name='medications',
            field=models.ManyToManyField(related_name='medications', to='api.medication'),
        ),
    ]
