# Generated by Django 4.0.7 on 2022-08-04 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportation',
            name='medications',
        ),
    ]
