# Generated by Django 4.0.7 on 2022-08-04 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_transportation_medications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportation',
            name='deliveredDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
